"""Prelude sort snapshot: extractor, renderer and the `harold-update-prelude-sorts` CLI.

The snapshot (`harold_mcp.heuristic.prelude_sorts`) is a generated Python module listing
the sorts the Maude prelude declares; rule 7 (`prelude-sort-redeclared`) and rule 6's
allow-list consume it, so a user program that shadows a prelude sort is reported, and
the built-in sorts have one source of truth.

The extraction reuses `iter_sort_declarations` — the same reader rule 7 runs on user
code — so the snapshot and the rule can never disagree on what a declaration is. This
module is also the only place that imports `cyclopts`; neither the provider nor the
rules depend on the CLI.

Regenerate the snapshot after a Maude upgrade:

    uv run harold-update-prelude-sorts /path/to/prelude.maude
    uv run harold-update-prelude-sorts /path/to/prelude.maude --check
"""

import hashlib
import importlib.util
import re
from collections import Counter
from collections.abc import Mapping
from datetime import date
from pathlib import Path
from typing import cast

from cyclopts import App

from harold_mcp.heuristic.declarations import iter_sort_declarations
from harold_mcp.heuristic.lexical import code_view

SNAPSHOT_PATH = Path(__file__).parent / "prelude_sorts.py"
"""Where the packaged snapshot lives (the CLI's default `--output`)."""

MINIMUM_SORT_NAMES = 50
"""Guard rail: a prelude declares hundreds of sorts, so fewer means the reader broke."""

_MAUDE_VERSION_RE = re.compile(r"Maude-([0-9][0-9.]*)")


def extract_prelude_sorts(text: str, excluded: Counter[str] | None = None) -> dict[str, str]:
    """Map every sort the prelude declares to the module that declares it.

    `excluded` accumulates the per-reason counts of the names the reader dropped (only a
    diagnostic aid for the CLI; the rules never pass it).
    """
    sorts: dict[str, str] = {}
    for declaration in iter_sort_declarations(code_view(text), excluded):
        # The first declaring module wins (the prelude declares a few names twice).
        if declaration.module is not None and declaration.name not in sorts:
            sorts[declaration.name] = declaration.module
    return sorts


def extract_prelude_sort_bases(sorts: Mapping[str, str]) -> frozenset[str]:
    """The declared names without their parameters (`List{X}` → `List`)."""
    return frozenset(name.split("{", 1)[0] for name in sorts)


def _infer_maude_version(prelude: Path) -> str:
    """Read the version out of a `Maude-<version>` path segment, else `unknown`."""
    match = _MAUDE_VERSION_RE.search(str(prelude))
    return match.group(1) if match else "unknown"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render_snapshot_module(
    sorts: Mapping[str, str],
    *,
    source_path: Path,
    source_hash: str,
    maude_version: str,
    extracted: str,
) -> str:
    """Render the generated snapshot module.

    The output is byte-stable for the same data: sorted, ASCII-only, exploded with a
    trailing comma (the layout `ruff format` keeps), so a regeneration either changes
    nothing or changes exactly the data.
    """
    modules = len(set(sorts.values()))
    lines = [
        '"""Snapshot of the sorts the Maude prelude declares (generated, do not edit).',
        "",
        "Generated by `harold-update-prelude-sorts`.",
        f"Maude version: {maude_version}",
        f"Source: {source_path}",
        f"Source SHA-256: {source_hash}",
        f"Extracted: {extracted}",
        f"Content: {len(sorts)} sort names declared by {modules} modules (theory sorts excluded).",
        "",
        "Regenerate after a Maude upgrade with `uv run harold-update-prelude-sorts <prelude.maude>`;",
        "`--check` verifies that the data still matches a fresh extraction.",
        '"""',
        "",
        "PRELUDE_SORTS: dict[str, str] = {",
    ]
    lines.extend(f'    "{name}": "{module}",' for name, module in sorted(sorts.items()))
    lines.extend(["}", "", "PRELUDE_SORT_BASES: frozenset[str] = frozenset({"])
    lines.extend(f'    "{base}",' for base in sorted(extract_prelude_sort_bases(sorts)))
    lines.append("})")
    return "\n".join(lines) + "\n"


def _load_snapshot_data(path: Path) -> tuple[dict[str, str], frozenset[str]]:
    """Import the snapshot module at `path` and return its two literals."""
    spec = importlib.util.spec_from_file_location("_harold_prelude_snapshot", path)
    if spec is None or spec.loader is None:  # pragma: no cover - a `.py` path always has a loader
        raise SystemExit(f"Cannot load the prelude sort snapshot at {path}")  # noqa: TRY003 - CLI error
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    namespace = module.__dict__
    return (
        cast("dict[str, str]", namespace["PRELUDE_SORTS"]),
        cast("frozenset[str]", namespace["PRELUDE_SORT_BASES"]),
    )


app = App(name="harold-update-prelude-sorts", help="Regenerate the bundled Maude prelude sort snapshot.")


@app.default
def main(
    prelude: Path,
    *,
    output: Path = SNAPSHOT_PATH,
    check: bool = False,
    maude_version: str | None = None,
) -> None:
    """Extract the sorts `<prelude>` declares and (re)write the bundled snapshot.

    Args:
        prelude: Path to the `prelude.maude` to extract the sorts from.
        output: Where the snapshot module lives (default: the packaged one).
        check: Only verify that `output` holds what a fresh extraction yields.
        maude_version: Version recorded in the provenance header (inferred from `prelude`
            when the path contains a `Maude-<version>` segment).
    """
    if not prelude.is_file():
        raise SystemExit(f"Not a Maude prelude file: {prelude}")  # noqa: TRY003 - CLI error
    text = prelude.read_text(encoding="utf-8", errors="replace")
    excluded: Counter[str] = Counter()
    sorts = extract_prelude_sorts(text, excluded)
    if len(sorts) < MINIMUM_SORT_NAMES:
        raise SystemExit(  # noqa: TRY003 - CLI error
            f"Refusing a snapshot with only {len(sorts)} sort names "
            f"(expected at least {MINIMUM_SORT_NAMES}): is {prelude} really a Maude prelude?"
        )
    print(f"Extracted {len(sorts)} sort names from {len(set(sorts.values()))} modules")
    for reason, count in sorted(excluded.items(), key=lambda item: (-item[1], item[0])):
        print(f"  excluded {reason}: {count}")
    if check:
        snapshot, bases = _load_snapshot_data(output)
        if snapshot == sorts and bases == extract_prelude_sort_bases(sorts):
            print(f"{output} is up to date")
            return
        raise SystemExit(  # noqa: TRY003 - CLI error
            f"{output} is out of date: regenerate it with `harold-update-prelude-sorts {prelude}`"
        )
    rendered = render_snapshot_module(
        sorts,
        source_path=prelude,
        source_hash=_sha256(prelude),
        maude_version=maude_version or _infer_maude_version(prelude),
        extracted=date.today().isoformat(),
    )
    if output.is_file() and output.read_text(encoding="utf-8") == rendered:
        print(f"{output} is already up to date")
        return
    _ = output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":  # pragma: no cover
    app()
